#!/usr/bin/env bash
# install load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:USER /etc/haproxy/haproxy.cfg

echo"
frontend leonardtech
    bind *:80
    mode http
    default_backend app

backend app
    balance roundrobin
    server 518415-web-01 54.161.236.197:80 check
    server 518415-web-02 35.175.129.69:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
